M48
; DRILL file KiCad 10.0.1 date 2026-05-04T15:55:20
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-04T15:55:20+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.750
%
G90
G05
T1
X75.017Y-64.126
X75.017Y-69.906
T2
X150.1Y-48.0
X151.9Y-48.0
X156.5Y-48.0
X158.3Y-48.0
M30
